services:
  gatherdle-prod-db:
    image: postgres:15
    container_name: gatherdle-prod-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gatherdle
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: gatherdle-web
    restart: always
    ports:
      - "80:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: gatherdle-prod-db
      DB_NAME: gatherdle
      DB_PORT: 5432
    depends_on:
      - gatherdle-prod-db
    command: sh -c "npm install && npm run migrate:up && npm run build && npm run start"
    volumes:
      - .:/app
   
    working_dir: /app

volumes:
  postgres_data: